pytorch/probot

- .circleci/config.yml
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>
> Add initial circleci pipeline

- src/trigger-circleci-workflows.ts
- test/trigger-circleci-workflows.test.ts
Adds the option to set all build parameters as true with `ci/all`
This basically allows users to run all of the workflows without needing
to specify anything.
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>
> Add ci/all to set all parameters to true

- Dockerfile
Lambdas don't seem to be able to function without these files so lets
just add them for safe-keeping
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>
> docker: Fix script to build for production

- src/trigger-circleci-workflows.ts
- test/trigger-circleci-workflows.test.ts
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>
> .circleci: Change to allow triggering on pull requests

- src/trigger-circleci-workflows.ts
This should make it easier to debug issues surrounding https://github.com/pytorch/pytorch/pull/58778.
> Add more logging in trigger-circleci-workflows.ts

- package.json
- yarn.lock
> Add @types/nock for type annotation

- src/ciflow-bot.ts
> Add logging about valid and rollout

- src/ciflow-bot.ts
- test/ciflow-bot.test.ts
* #45
* __->__ #44
----
Adding the support for comment author's permission.
The comment author can 1) either be the pr author, `OR` 2) they have the write or admin permission to be able to trigger the pytorchbot commands.
> Add comment author permission check

- src/ciflow-bot.ts
- test/ciflow-bot.test.ts
> Fix comment parsing and labels to add with zero length

- package.json
- src/ciflow-bot.ts
- test/ciflow-bot.test.ts
- yarn.lock
* #47
* __->__ #46
```
@pytorchbot ciflow rerun
@pytorchbot ciflow rerun -l ciflow/scheduled
@pytorchbot ciflow rerun -l ciflow/scheduled -l ciflow/slow
```
> Add ciflow commands with label args

- src/ciflow-bot.ts
- test/ciflow-bot.test.ts
* __->__ #47
* #46
The probot will just 👍 to the comment if it works.
> Add +1 reaction to the comments successfully dispatched

- .gitignore
- src/ciflow-bot.ts
- test/ciflow-bot.test.ts
* __->__ #51
Demo link: https://github.com/zhouzhuojie/gha-ci-playground/pull/33#issuecomment-898782956
> Adding ciflow ruleset visualization

- src/ciflow-bot.ts
- test/ciflow-bot.test.ts
I was deciding between the two options and prefer option 1 for its simplicity and readability. Option 2 simply hides the comment without too much context.
Demo link: https://github.com/zhouzhuojie/gha-ci-playground/pull/35
> Minimize comment and use a dedicated comment block

- src/ciflow-bot.ts
- test/ciflow-bot.test.ts
- Add `allowed_repos` so that ciflow-bot only runs on certain repos - currently only `pytorch/pytorch`
> Add allowed repos gating

- src/auto-cc-bot.ts
- test/auto-cc-bot.test.ts
Fixes https://github.com/pytorch/pytorch-probot/issues/60
> Auto-CC should work for issues with empty bodies

- src/ciflow-bot.ts
- test/ciflow-bot.test.ts
If PR is created with pre-existing ciflow/ labels, do not add new ones
ot it
> [CIFlow] Do not override user choice

- src/ciflow-bot.ts
- test/ciflow-bot.test.ts
- test/ciflow-parse.test.ts
- Respect the user config setting of default labels from the issue tracker
- Respect the opt-out users from the issue tracker
- Refactor the code a little bit with IUserConfig interface
> Rollout ciflow to everyone

- src/verify-disable-test-issue.ts
> fix verify bot: issue_number instead of issueNumber

- src/auto-label-bot.ts
- test/auto-label-bot.test.ts
> Automatically label DISABLED issues with skipped

- src/ciflow-bot.ts
> Prevent Bot from adding Labels for Rerun Comments
